language: python
python: "3.6"

install:
# build dependencies
  - pip install numpy matplotlib pillow scikit-image scipy h5py scikit-learn opencv-python tensorflow keras
# test dependencies
  - pip install coveralls
  - pip install pytest pytest-cov

script:
  - pytest -v src/test/ --cov=retipy --cov-report term-missing

after_success:
  coveralls
