language: python
python: "3.6"

install:
# build dependencies
  - pip install --user -e src/
# test dependencies
  - pip install coveralls
  - pip install pytest pytest-cov

script:
  - pytest -v src/test/ --cov=retipy --cov-report term-missing

after_success:
  coveralls
